### ISSUE TITLE
Sudden error while compiling

### ISSUE THREAD

**Issue by ItayRosen** [adafruit/Adafruit_BNO055#58]
Hello,

I've been using Arduino Create for working on past projects. I've been using BNO055 with Arduino Mini Pro for the past few months with satisfaction. However, today, a new issue has risen with the library.

The issue rises as early as including the library without any code manipulation yet. The relevant code:
`#include <Adafruit_Sensor.h>
#include "Adafruit_BNO055.h"
#include <utility/imumaths.h>`

The error I'm getting when trying to compile:
`In file included from /home/ubuntu/opt/libraries/latest/bno055simplepacketcoms_0_0_1/src/GetIMU.h:12:0,

from /home/ubuntu/opt/libraries/latest/bno055simplepacketcoms_0_0_1/src/GetIMU.cpp:8:

/home/ubuntu/opt/libraries/latest/simplepacketcoms_0_0_6/src/SimplePacketComs.h:5:18: fatal error: vector: No such file or directory

#include <vector>

^

compilation terminated.

exit status 1`

First time that I'm having trouble with the library. Any ideas?

**Comment by ladyada** [comment]
/home/ubuntu/opt/libraries/latest/simplepacketcoms_0_0_6/src/SimplePacketComs.h

is not something that we have in this library? please check your code for where this file is referenced. :)

**Comment by madhephaestus** [comment]
It would seem my library caused this issue. The reason for it is that Adafruit_Sensor.h is not provided by an official library anywhere. the only library providing it is my ESP32 server version that had to include it because of compilation errors otherwise. @ladyada Would it be possible for you to make an official  Adafruit_Sensor.h stand alone Arduino library? Or modify some standard library to provide Adafruit_Sensor.h and Ill remove this line: https://github.com/madhephaestus/BNO055SimplePacketComs/blob/master/library.properties#L10

then re-publish my library depending on your standard implementation of Adafruit_Sensor.h 

Or perhaps i'm missing something obvious, where is one supposed to get Adafruit_Sensor.h?

It seems the simple solution that Arduino came up with is to de-list bno055simplepacketcoms without telling me :/ Good thing i caught this before my class started Wednesday...

**Comment by ladyada** [comment]
thanks @madhephaestus - that's good to know :)

**Comment by ladyada** [comment]
ok i bumped the sensor library to 1.0.3

**Comment by madhephaestus** [comment]
@ladyada Thank you, you rock!

**Comment by ladyada** [comment]
no, YOU rock!!!
